name: Deploy to Azure VM (Dev)

on:
  push:
    branches:
      - dev-release

env:
  IMAGE_NAME: hiransanjeewa/research-bucks
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-push:
    name: Build & Push Docker Image with Buildpacks
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file dynamically
        run: |
          echo "NEXT_PUBLIC_API_BASE=http://${{ secrets.AZURE_VM_IP }}:8060/" > .env
          cat .env
  
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push $IMAGE_NAME:latest


  deploy:
    name: Deploy Docker Image on Azure VM
    runs-on: ubuntu-latest
    environment: Dev
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull $IMAGE_NAME:latest
            echo "Stopping existing container (if exists)..."
            docker stop research-bucks-f 2>/dev/null || echo "No existing container to stop"

            echo "Removing existing container (if exists)..."
            docker rm research-bucks-f 2>/dev/null || echo "No existing container to remove"

            docker run -d -p 80:3000 --name research-bucks-fe $IMAGE_NAME:latest


